FROM node:6.12.3

RUN apt-get update && \
    apt-get install -y \
    build-essential

RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY ./frontend /usr/src/app

RUN npm install && \
    npm run build && \
    npm install -g serve

CMD ["serve", "-s", "build"]